declare module 'next-auth'
declare module 'next-auth/providers'
declare module 'next-auth/client'
declare module 'metascraper'
declare module 'metascraper-title'
declare module 'metascraper-url'
declare module 'metascraper-description'
declare module 'metascraper-date'